window.SESSION_LIBRARY = {
  "updated_at": "2026-03-27T22:56:31",
  "session_count": 6,
  "sessions": [
    {
      "slug": "2026-03-28-snowlight-in-finland",
      "date": "2026-03-28",
      "title": "Snowlight In Finland",
      "subtitle": "A northern winter night practice shaped by snowlight, timber warmth, and the hush of a Finnish cabin",
      "kind": "audio",
      "kindLabel": "Audio Session",
      "meta": "Sleep Meditation",
      "description": "A northern winter night practice shaped by snowlight, timber warmth, and the hush of a Finnish cabin Best played in a quiet room while your breathing and body gradually soften.",
      "mediaPath": "./output/2026-03-28-snowlight-in-finland/voiceover.mp3",
      "publicMediaPath": "https://come-to-sleep-by-leo-chan.pages.dev/output/2026-03-28-snowlight-in-finland/voiceover.mp3",
      "posterPath": "./output/2026-03-28-snowlight-in-finland/2026-03-28-snowlight-in-finland-image.png",
      "publicPosterPath": "https://come-to-sleep-by-leo-chan.pages.dev/output/2026-03-28-snowlight-in-finland/2026-03-28-snowlight-in-finland-image.png",
      "coverTheme": "warm-cover"
    },
    {
      "slug": "2026-03-27-lanterns-after-rain-2",
      "date": "2026-03-27",
      "title": "Lanterns After Rain",
      "subtitle": "A warm voice-led night practice for the hour when the world has finally gone quiet again",
      "kind": "audio",
      "kindLabel": "Audio Session",
      "meta": "Sleep Meditation · Rainy Night Atmosphere",
      "description": "A warm voice-led night practice for the hour when the world has finally gone quiet again Best played in a quiet room while your breathing and body gradually soften.",
      "mediaPath": "./output/2026-03-27-lanterns-after-rain-2/voiceover.mp3",
      "publicMediaPath": "https://come-to-sleep-by-leo-chan.pages.dev/output/2026-03-27-lanterns-after-rain-2/voiceover.mp3",
      "posterPath": "./output/2026-03-27-lanterns-after-rain-2/2026-03-27-lanterns-after-rain-2-image.png",
      "publicPosterPath": "https://come-to-sleep-by-leo-chan.pages.dev/output/2026-03-27-lanterns-after-rain-2/2026-03-27-lanterns-after-rain-2-image.png",
      "coverTheme": "warm-cover"
    },
    {
      "slug": "2026-03-22-the-empty-boat-2",
      "date": "2026-03-22",
      "title": "The Empty Boat",
      "subtitle": "A voice-only night drift for letting thoughts pass and settling into unforced sleep",
      "kind": "audio",
      "kindLabel": "Audio Session",
      "meta": "Sleep Meditation",
      "description": "A voice-only night drift for letting thoughts pass and settling into unforced sleep Best played in a quiet room while your breathing and body gradually soften.",
      "mediaPath": "./output/2026-03-22-the-empty-boat-2/voiceover.mp3",
      "publicMediaPath": "https://pub-295d6824d61a475586e432fe9e260d8e.r2.dev/2026-03-22-the-empty-boat-2/voiceover.mp3",
      "posterPath": "./output/2026-03-22-the-empty-boat-2/2026-03-22-the-empty-boat-2-image.png",
      "publicPosterPath": "https://come-to-sleep-by-leo-chan.pages.dev/output/2026-03-22-the-empty-boat-2/2026-03-22-the-empty-boat-2-image.png",
      "coverTheme": "warm-cover"
    },
    {
      "slug": "2026-03-22-after-the-mind-lets-go-3",
      "date": "2026-03-22",
      "title": "After The Mind Lets Go",
      "subtitle": "A gentle night practice for overthinking minds that need a softer way to unwind",
      "kind": "audio",
      "kindLabel": "Audio Session",
      "meta": "Sleep Meditation",
      "description": "A calming sleep session for nights of overthinking, with softer breath guidance and a clearer path out of mental looping. Made for the kind of bedtime when the body is ready, but the mind has not yet learned how to let go.",
      "mediaPath": "./output/2026-03-22-after-the-mind-lets-go-3/voiceover.mp3",
      "publicMediaPath": "https://pub-295d6824d61a475586e432fe9e260d8e.r2.dev/2026-03-22-after-the-mind-lets-go-3/voiceover.mp3",
      "posterPath": "./output/2026-03-22-after-the-mind-lets-go-3/2026-03-22-after-the-mind-lets-go-3-image.png",
      "publicPosterPath": "https://come-to-sleep-by-leo-chan.pages.dev/output/2026-03-22-after-the-mind-lets-go-3/2026-03-22-after-the-mind-lets-go-3-image.png",
      "coverTheme": "warm-cover"
    },
    {
      "slug": "2026-03-19-the-quiet-room",
      "date": "2026-03-19",
      "title": "The Quiet Room",
      "subtitle": "A still, voice-led night practice shaped by simple presence and soft breath",
      "kind": "audio",
      "kindLabel": "Audio Session",
      "meta": "Sleep Meditation",
      "description": "A quieter, more spacious sleep session for nights that feel mentally full. Built around simple presence and a softer, Zen-shaped way of letting thought pass without following it.",
      "mediaPath": "./output/2026-03-19-the-quiet-room/voiceover.mp3",
      "publicMediaPath": "https://pub-295d6824d61a475586e432fe9e260d8e.r2.dev/2026-03-19-the-quiet-room/voiceover.mp3",
      "posterPath": "./output/2026-03-19-the-quiet-room/2026-03-19-the-quiet-room-image.png",
      "publicPosterPath": "https://come-to-sleep-by-leo-chan.pages.dev/output/2026-03-19-the-quiet-room/2026-03-19-the-quiet-room-image.png",
      "coverTheme": "warm-cover"
    },
    {
      "slug": "2026-03-19-still-waters-at-night-2",
      "date": "2026-03-19",
      "title": "Still Waters At Night",
      "subtitle": "A voice-led night practice for deep unwinding and sleep",
      "kind": "audio",
      "kindLabel": "Audio Session",
      "meta": "Sleep Meditation",
      "description": "A deeply unwinding sleep meditation with a steady human voice, slower exhales, and long settling pauses. Made for nights when the body is tired but the mind is still gently moving.",
      "mediaPath": "./output/2026-03-19-still-waters-at-night-2/voiceover.mp3",
      "publicMediaPath": "https://pub-295d6824d61a475586e432fe9e260d8e.r2.dev/2026-03-19-still-waters-at-night-2/voiceover.mp3",
      "posterPath": "./output/2026-03-19-still-waters-at-night-2/2026-03-19-still-waters-at-night-2-image.png",
      "publicPosterPath": "https://come-to-sleep-by-leo-chan.pages.dev/output/2026-03-19-still-waters-at-night-2/2026-03-19-still-waters-at-night-2-image.png",
      "coverTheme": "warm-cover"
    }
  ]
};
